---
title: "On and Around Campus"
---

## The Campus

The UCSB campus is situated right along the coastline, with several buildings (including our very own South Hall) featuring views of the water. The campus also houses a Lagoon, which is home to a number of wildlife species. Our department (the Department of Statistics and Applied Probability) is located on the fifth floor of <b>South Hall</b>, which houses many other departments including Mathematics, Economics, Linguistics, and a few others.

\

The PSTAT department has offices split across several buildings:

  - **South Hall:** Nearly all professors, and most upper-year graduate students
  have offices on the fifth floor of South Hall. The department Main Office is also on the fifth floor.

  

  - **Building 434:** Most first- and second-year graduate students have offices located in Building 434, located directly adjacent to South Hall.


  - **The Old Gymnasium (a.k.a. "The Barn"):** Several visiting faculty have offices in the Old Gym, which is located diagonally adjacent to South Hall. The Disabled Students Program (DSP) also has an office in the Old Gym.



\

## The Surroundings

The nearest "city" to campus is Isla Vista (commonly referred to as "IV"), though it is perhaps better labelled a "township" than a "city". Campus actually shares a border with IV, making the township very easy to access from campus.

\

## Getting To and From UCSB

The nearest airport to campus is the Santa Barbara Airport (SBA), located just a 5-minute drive and a
17-minute bus ride from campus (the line 11 connects the North Hall Busloop and SBA). Though SBA is quite convenient for many domestic flights, be warned that it is a smaller airport and is not well-suited for long-distance travel; there are relatively few flights directly connecting SBA to non-west-coast airports, and there are zero international flights routing through SBA. The nearest larger airport is LAX (Los Angeles International Airport), located around 2 hours away by car (there also exists a shuttle between UCSB and LAX). \

The main highway is Highway 101: it originates in San Francisco and runs through Santa Maria, Goleta, Santa Barbara, Carpinteria, Ventura, Oxnard, Camarillo, and terminates in Los Angeles.

\


<h2>Food and Drink</h2>

If you are looking for a place to eat on Campus, your options are admittedly a bit limited. Current food options include:

<ul>
  <li><a href= "https://ucen.ucsb.edu/" target = "_blank">The UCen (University Center):</a> The UCen is the main on-campus center, functioning much like a
  Student Union Building. In addition to housing the University Bookstore, it also houses a few food options including: Panda Express, Root,
  Jamba Juice, Subway, and Santorini Island Grill. The dining-specific page of the UCen can be found <a href = "https://ucen.ucsb.edu/dining" target = "_blank">here</a>,</li>

  <br>

  <li><a href= "https://dining.ucsb.edu/eateries-markets" target = "_blank">On-Campus "Markets:"</a> There are also a handful of "Markets" located throughout Campus. The main
  such establishment is <b>The Arbor</b>, which conveniently is the closest establishment to South Hall (where the PSTAT department is housed). The Arbor
  stocks snaks and drinks, and also houses a Subway along with a Woodstock's Pizza location around the corner. </li>

  <br>

  <li><b><u>The Hot Dog Cart:</u></b></a> Official sources list this as <i>Die Brezel</i> (German for "the Pretzel"), though you will often hear this colloquially referred to
  as "The Hot Dog Cart." One of the perhaps most underrated establishments on campus, this cart offers fresh-baked pretzels and hotdogs (with vegetarian options as well!),
  and is located just outside The Arbor.</li>

  <br>

  <li><b><u>Yoshinoya:</u></b> The only Japanese-themed eatery on campus, the UCSB branch of <i>Yoshinoya</i> (which is admittedly a chain) is located in the Courtyard Café,
  near the Physics building. Though perhaps a bit far from South Hall, the food is usually worth the trek!</li>
</ul>

<br>
<br>

There are a few more options off-Campus, in the city of Isla Vista. Some highlights in IV include:

<ul>
  <li><b><u>Cajé:</u></b> Cajé is a moderately-sized coffee shop, offering smoothies and smoothie bowls along with bagels (and, of course, your typical spread of café beverages:
    their Matcha Latté's are quite good!) There are only limited power outlets, though, so be aware of that if you are planning on studying for a while!</li>

    <br>

  <li><b><u>IV Drip:</u></b> The IV Drip is open fairly late, and boasts some of the <b>best</b> cookies around. (Several officers of this committee can personally attest!)</li>

    <br>

  <li><b><u>Phở Bistro:</u></b> If you're looking for fairly large portions at fairly decent prices, Phở Bistro is the place to go!</li>

    <br>

  <li><b><u>Woodstocks:</u></b> Woodstocks Pizza is well-known among UCSB students. Though quite pricey, their pizzas are quite good, featuring thick crusts and copious toppings. Woodstocks also sports a hefty array of beers, making it a popular haunt among graduate students. On Thursday Nights they also host a Trivia Night at 9pm.</li>

   <br>
   
   <li><b><u>IV Pizza and Pub:</u></b> formerly a location of <i>Pizza my Heart</i>, the newly-opened IV Pizza and Pub serves up large New-York style slices of pizzas at a decently affordable price (at least, for IV). Management claims that beers and wines planned to be offered soon...
   
   <br>

  <li><b><u>Freebirds:</u></b> Freebirds is fairly typical when it comes to Chipotle-style mexican restaurants (in the sense that food is made right in front of you), though Freebirds has the added benefit of being open fairly late (for IV) on most nights.</li>

  <br>

 <li><b><u>Blenders in the Grass:</u></b> A fairly common Smoothie/Juice-Bar chain, serving up decent smoothies and bowls for the slightly more health-conscious.</li>

   <br>

  <li><b><u>Various Others!</u></b> This list is by no means comprehensive!</li>

</ul>
