---
title: "Santa Barbara"
---


Though Isla Vista is the closest township to UCSB, it is admittedly a bit limited in what it offers. As such, it is fairly common for UCSB students to venture out to downtown Santa Barbara, either by car (12 minutes) or by bus (30 minutes via the 24X, 1hr via the 11).

\

There are (roughly) four distinct areas in Santa Barbara: State Street (sometimes called Lower State Street), Upper State Street, the Funk Zone, and the Mission. State Street boasts the most activities, both in terms of day-life and nightlife, whereas the Funk Zone excels primarily in its unique nighlife scene. 

\

Some recommendations for places to study in SB:

- **Cajé**: Yes, this is the same Cajé that has a location in IV. But their location along Arlington street is quite a sight to behold! Formerly a Greek restaurant called *Petros*, Cajé retains a number of the chefs and staff from Petros and, as a result, offers an elegant and delicious spread of high-end Greek food! Additionally, the Arlington Cajé boasts a wide array of specialty drinks (non-alcoholic, but still a sight to behold). Be warned that outlets are limited, and that the majority of seating is outdoors. 

- **Lighthouse Coffee:** With several locations throughout SB, Lighthouse Coffee is a popular study spot among UCSB students. A major selling point is the *ample* presence of power outlets- a bit of a rarity in SB coffee shops!

<br>