---
title: "Events"
---

<iframe src="https://calendar.google.com/calendar/embed?src=pstat.grad.committee%40gmail.com&ctz=America%2FLos_Angeles" style="border: 0" width="700" height="450" frameborder="0" scrolling="no"></iframe>

\

## Current and Upcoming Events (as of Winter Quarter 2023)

_**Stay Tuned for more updates soon!**_


\

## Archive of Events:

::: {.callout-note appearance="default" collapse="true"}

## Archive: Fall 2022


- <a href="../Images/Event_Flyers/Archives/F22/Fall22_BBQ.png" target="_blank"><b>Our Third BBQ as  a Committee!</b></a> 

- <a href="../Images/Event_Flyers/Archives/F22/f22_tea_updated.png" target="_blank"><b>Tea Time Continues (with a mid-quarter change to incorporate Seminar Snacks!)</b></a> 

:::


::: {.callout-note appearance="default" collapse="true"}

## Archive: Spring 2022


- <a href="../Images/Event_Flyers/Archives/SP22/sp22_bbq.png" target="_blank"><b>The very first Spring Barbecue for our Department!</b></a> 

:::

::: {.callout-note appearance="default" collapse="true"}

## Archive: Fall 2021


- <a href="../Images/Event_Flyers/Archives/F21/f21_bbq.png" target="_blank"><b>Our very first in-person BBQ!</b></a> 

- <a href="../Images/Event_Flyers/Archives/F21/tour_and_snacks.png" target="_blank"><b>Our first Walking-Tour-and_Snacks Event!</b></a> In Fall 2021, we hosted a walking tour of campus (followed by light refreshments) designed to help new students (and, indeed, students who first arrived on campus in 2020) get oriented.

:::


::: {.callout-note appearance="default" collapse="true"}

## Archive: Winter 2021


- <a href="../Images/Event_Flyers/Archives/W21/w21_tea_time.png" target="_blank"><b>Tea-Time Returns!</b></a> 

:::


::: {.callout-note appearance="default" collapse="true"}

## Archive: Fall 2020

**Fun Fact:** Fall 2020 marked our inaugural quarter as a committee! (This is also why our flyers for this quarter have a bit of an, ahem, *retro* feel...)

- <a href="../Images/Event_Flyers/Archives/F20/Grad_Happy_Hour.png" target="_blank"><b>Our First Social Event: Graduate Student Happy Hour!</b></a> We're excited to announce our first social event of the semester! On Monday September 28, 2020 at 7:30pm, we will be hosting a Graduate Students Happy Hour. There will be games, activities, and plenty of opportunities to meet your fellow PSTAT grad students! Check out our discord channel for the Zoom Link.

- <a href="../Images/Event_Flyers/Archives/F20/tea_final_flyer.png" target="_blank"><b>Our First Set of Weekly Events: Afternoon <i>t</i>-Time</b></a> Time for *t* distributions - I mean, Tea! Join us every Friday at 5pm for a chance to unwind with your fellow PSTAT grad students, all over a nice cup of steaming hot tea. 


:::
